#!/bin/bash

HISTCONTROL=ignoreboth
HISTSIZE=5000
HISTFILESIZE=100000

shopt -s histappend
shopt -s checkwinsize

[ -e "$WORKSPACE" ] || WORKSPACE="$HOME/Workspace"
export WORKSPACE

## window title
title() {
  t="${USER}@${HOSTNAME}: $*"
  echo -n "";
}

function __git_dirty {
  git diff --quiet HEAD &>/dev/null
  [ $? == 1 ] && echo "*"
}

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls -G'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

#export PS1="\[\033[01;34m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[33m\]\$(parse_git_branch)\$(parse_svn_branch)\[\033[0;31m\]\$(__git_dirty)\[\033[00m\]$ "
export PS1="\[\033[36m\]\u@\[\033[36m\]\h:\w \[\033[33m\]\$(parse_git_branch)\$(parse_svn_branch)\[\033[00m\]\$(__git_dirty)\[\033[00m\]$ "
export CLICOLOR=1
export LESS="-RX"
export EDITOR="vi"
export TERM=xterm-color

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
export IDEA_JDK=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
export WEBIDE_JDK=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home

export NODE_ENV=development
export RACK_ENV=development
export PLAY_ENV=development

export CHROME_BIN=/usr/bin/chromium-browser

export GOROOT=/usr/local/go
export GOPATH=~/Workspace/go

export PATH=$GOROOT/bin:/usr/local/share/scala/bin:/usr/local/bin:/usr/local/jmeter-2.13/bin:~/Workspace/go/bin:$PATH

export PIP_REQUIRE_VIRTUALENV=true

export HB_WORKSPACE=~/Workspace/hb
export SELENIUM_SERVER_JAR=~/Workspace/hb/hb-cloud-tests/jar/selenium-server-standalone-2.42.2.jar
export SELENIUM_BROWSER=chrome

# Go helpers
CDPATH=.:$GOPATH/src/github.com:~/Workspace
#
gocd () {
    cd `go list -f '{{.Dir}}' $1`
}

#. ~/.aws/keys.sh

function ssht() {
  if [ "$1" = "" ] ; then
       echo "Invalid server name"
       return
  fi
  fname=$( date +"$1_%y_%m_%H_%M_%S" )
  ssh $1 | tee ~/Workspace/sshlogs/$fname.log
}

gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
