#!/bin/bash

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

shopt -s histappend
shopt -s checkwinsize

[ -e "$WORKSPACE" ] || WORKSPACE="$HOME/Workspace"
export WORKSPACE

## window title
title() {
  t="${USER}@${HOSTNAME}: $*"
  echo -n "";
}

function __git_dirty {
  git diff --quiet HEAD &>/dev/null
  [ $? == 1 ] && echo "*"
}

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

#export PS1="\[\033[01;34m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[33m\]\$(parse_git_branch)\$(parse_svn_branch)\[\033[0;31m\]\$(__git_dirty)\[\033[00m\]$ "
export PS1="\[\033[36m\]\u@\[\033[36m\]\h:\w \[\033[33m\]\$(parse_git_branch)\$(parse_svn_branch)\[\033[00m\]\$(__git_dirty)\[\033[00m\]$ "
export CLICOLOR=1
export LESS="-RX"
export EDITOR="vi"
export TERM=xterm-color

export JAVA_HOME=/usr/lib/jvm/java-7-oracle
export ANDROID_HOME=~/opt/local/android-sdk
export M2_HOME=~/opt/local/apache-maven-3.0.5

export NODE_ENV=development
export RACK_ENV=development

export PATH=$PATH:~/opt/local/android-sdk/tools:~/opt/local/android-sdk/platform-tools:~/opt/local/apache-maven-3.0.5/bin:~/Workspace/dotfiles/support
cd ~/Workspace
